spring.application.name=05_mybatis_supa

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.uncogyonzyahmxhernhq
spring.datasource.password=XX.23z&raFHLshH