spring.application.name=07_RestApi_store

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.uncogyonzyahmxhernhq
spring.datasource.password=XX.23z&raFHLshH

# HikariCP 설정 - 최대 연결 풀 크기 설정
#spring.datasource.hikari.maximum-pool-size=3
#
## HikariCP 설정 - 최소 유휴 연결 수 (선택 사항)
#spring.datasource.hikari.minimum-idle=2
#
## 연결 테스트 타임아웃 (Supabase 연결이 불안정할 경우 유용)
## 30초 (밀리초 단위)
#spring.datasource.hikari.connection-timeout=30000